package CalcApp.CalcPackage;


/**
* CalcApp/CalcPackage/CalcError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Thursday, October 22, 2015 6:12:35 PM PDT
*/

public final class CalcError extends org.omg.CORBA.UserException
{

  public CalcError ()
  {
    super(CalcErrorHelper.id());
  } // ctor


  public CalcError (String $reason)
  {
    super(CalcErrorHelper.id() + "  " + $reason);
  } // ctor

} // class CalcError
