package CalcApp.CalcPackage;

/**
* CalcApp/CalcPackage/CalcErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Thursday, October 22, 2015 6:12:35 PM PDT
*/

public final class CalcErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public CalcApp.CalcPackage.CalcError value = null;

  public CalcErrorHolder ()
  {
  }

  public CalcErrorHolder (CalcApp.CalcPackage.CalcError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalcApp.CalcPackage.CalcErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalcApp.CalcPackage.CalcErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalcApp.CalcPackage.CalcErrorHelper.type ();
  }

}
