package CalcApp;


/**
* CalcApp/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Thursday, October 22, 2015 6:12:35 PM PDT
*/

public interface CalcOperations 
{
  double calculate (String opcode, double op1, double op2) throws CalcApp.CalcPackage.DivisionByZero, CalcApp.CalcPackage.CalcError;
  void shutdown ();
} // interface CalcOperations
